### ISSUE TITLE
Repository description.

### ISSUE THREAD

**Issue by philipbrito** [cusspvz/btsync.docker#2]
Hi @cusspvz, I forked your repository to make a simple thing: Change the repository description ("A 32MB docker image sync service built for persist data on clusters").

As is impossible to send this change by a pull request I'd like notify that this description is different in relation to README.md, where you write: "A **40MB** docker image sync service built for persist data on clusters".

Good work. 
:)

**Comment by cusspvz** [comment]
Thanks for noticing that @filipedelimabrito , I did a total refactoring where I have also changed the base image to my [node.docker](/cusspvz/node.docker) to shrink its final size and forgot to update it.

Cheers :smile:
